# .scrutinizer.yml

checks:
    php:
        code_rating: true
        duplication: true

build:
    nodes:
        tests: true
        analysis:
            tests:
                override:
                    -
                        command: phpcs-run
                        use_website_config: true
                    - php-scrutinizer-run
 
