# .scrutinizer.yml

checks:
    php: true
    javascript: true
filter: {  }
coding_style:
    php:
        spaces:
            around_operators:
                concatenation: true
build:
     nodes:
         analysis:
             tests:
                 override:
                     - php-scrutinizer-run
                     - js-scrutinizer-run
